<?php
require_once dirname(__FILE__) . '/../../lib/XSServer.class.php';

/**
 * Test class for XSCommand.
 * Generated by PHPUnit on 2011-09-15 at 19:29:49.
 */
class XSCommandTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var XSCommand
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new XSCommand(CMD_NONE);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		
	}

	public function test__toString()
	{
		$this->object->buf1 = str_repeat('-', 255);
		$this->assertEquals(8 + strlen($this->object->buf1), strlen($this->object));

		$this->object->buf1 .= '_';
		$this->assertEquals(7 + strlen($this->object->buf1), strlen($this->object));
	}

	public function testGetArg()
	{
		$this->object->arg2 = 5;
		$this->object->arg1 = 2;
		$arg = ((2 << 8) | 5);		
		$this->assertEquals($arg, $this->object->arg);
		$this->assertEquals($this->object->arg, $this->object->getArg());
		
		$cmd2 = new XSCommand(array('arg1' => 2, 'arg2' => 5));
		$this->assertEquals($arg, $cmd2->arg);
	}

	public function testSetArg()
	{
		$arg = ((2 << 8) | 5);
		$this->object->arg = $arg;
		$this->assertEquals(2, $this->object->arg1);
		$this->assertEquals(5, $this->object->arg2);
	}
}
