<?php
require_once dirname(__FILE__) . '/../../lib/XS.class.php';

/**
 * Test class for XSException.
 * Generated by PHPUnit on 2011-07-23 at 20:26:03.
 */
class XSExceptionTest extends PHPUnit_Framework_TestCase
{

	public function test__toString()
	{
		try
		{
			throw new XSException('Test without code');
		}
		catch (XSException $e1)
		{
			
		}
		try
		{
			throw new XSException('Test with code', 400);
		}
		catch (XSException $e2)
		{
			
		}
		$this->assertInstanceOf('XSException', $e1);
		$this->assertEquals('[XSException] lib/XSExceptionTest.php(15): Test without code', strval($e1));
		
		$this->assertInstanceOf('XSException', $e2);
		$this->assertEquals('[XSException] lib/XSExceptionTest.php(23): Test with code(S#400)', '' . $e2);
	}

	public function testGetRelPath()
	{
		$this->assertEquals('lib/XSExceptionTest.php', XSException::getRelPath(__FILE__));
		$this->assertEquals('/phpunit.xml', XSException::getRelPath(dirname(__FILE__) . '/../phpunit.xml'));
		$this->assertEquals('../lib/XS.class.php', XSException::getRelPath('../../php/lib/XS.class.php'));
		XSException::getRelPath('/dev');
	}
}
