<?php
require_once dirname(__FILE__) . '/../../lib/XS.class.php';

/**
 * Test class for XS.
 * Generated by PHPUnit on 2011-07-23 at 20:26:04.
 */
class XSTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var XS
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		
	}

	/**
	 * @todo Implement testGetScheme().
	 */
	public function testGetScheme()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetScheme().
	 */
	public function testSetScheme()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testRestoreScheme().
	 */
	public function testRestoreScheme()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetName().
	 */
	public function testGetName()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetDefaultCharset().
	 */
	public function testGetDefaultCharset()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetIndex().
	 */
	public function testGetIndex()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetSearch().
	 */
	public function testGetSearch()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetFieldId().
	 */
	public function testGetFieldId()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetField().
	 */
	public function testGetField()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetAllFields().
	 */
	public function testGetAllFields()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	public function testConvert()
	{
		$str = 'english string only';		
		$this->assertEquals(XS::convert($str, 'GBK', 'UTF-8'), $str);
		
		$str = 'english 和中文混合';
		$str1 = XS::convert($str, 'GBK', 'UTF-8');
		$this->assertEquals(XS::convert($str1, 'UTF-8', 'GBK'), $str);	
	}
}

?>
